// Generated by CoffeeScript 1.3.3
(function() {
  var render_board, server_url, update;

  server_url = "http://10.156.25.207:5000";

  update = function() {
    return $.ajax({
      url: server_url,
      data: {
        x: 1,
        y: 1
      },
      success: function() {
        return render_board;
      }
    });
  };

  render_board = function(data) {
    var board;
    board = $("#board_wrapper");
    board.html("");
    return board.html(data);
  };

  $(function() {
    return update();
  });

}).call(this);
